jar 'net.java.dev.jna:jna', '4.2.1'
jar 'org.slf4j:slf4j-api', '> 1.7.11'
jar 'ch.qos.logback:logback-core', '> 1.0'
jar 'ch.qos.logback:logback-classic', '> 1.0'
jar 'org.pcap4j:pcap4j-core', '> 1.0', '< 2.0'
jar 'org.pcap4j:pcap4j-packetfactory-static', '> 1.0', '< 2.0'
